/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <iostream>
#include "utils/ArrayUtils.h"
#include "spdlog/spdlog.h"

/**
 * creates an empty particle
 * @param type_arg
 */
Particle::Particle(int type_arg) {
  type = type_arg;
  //spdlog::info("Particle generated!");
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
}

/**
 * makes an copy of another particle
 * @param other
 */
Particle::Particle(const Particle &other) {
  x = other.x;
  oldX = other.oldX;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  sig = other.sig;
  eps = other.eps;
  //spdlog::info("Particle generated by copy!");
}

/**
 * creates a new Particle
 * @param x_arg position coordinates
 * @param v_arg velocity
 * @param m_arg mass
 * @param sig sigma
 * @param eps epsilon
 * @param type_arg particle type
 */
Particle::Particle(std::array<double, 3> x_arg, std::array<double, 3> v_arg,
                   double m_arg, double sigma, double epsilon, int type_arg) {
    x = x_arg;
    oldX = x;
    v = v_arg;
    m = m_arg;
    type = type_arg;
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
    sig = sigma;
    eps = epsilon;
}

Particle::~Particle() = default;

/**
 * returns current position of particle
 * @return current position coordinates
 */
const std::array<double, 3> &Particle::getX() const { return x; }

/**
 * returns previous position of particle
 * @return previous position coordinates
 */
const std::array<double, 3> &Particle::getOldX() const {return oldX;}

/**
 * returns velocity of particle
 * @return velocity
 */
const std::array<double, 3> &Particle::getV() const { return v; }

/**
 * returns force of particle
 * @return force
 */
const std::array<double, 3> &Particle::getF() const { return f; }

/**
 * returns old force of particle
 * @return old force
 */
const std::array<double, 3> &Particle::getOldF() const { return old_f; }

/**
 * returns mass of particle
 * @return mass
 */
double Particle::getM() const { return m; }

/**
 * returns type of particle
 * @return type
 */
int Particle::getType() const { return type; }

/**
 * returns sigma of particle
 * @return sigma
 */
 double Particle::getSig() const {return sig;}

 /**returns epsilon of particle
  * @return epsilon
  */
  double Particle::getEps() const {return eps;}

/**
 * returns particle as string
 * @return string representation
 */
std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f
         << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

/**
 * comparison with another particle
 * @param other particle to compare to
 * @return
 */
bool Particle::operator==(Particle &other) {
  return (x == other.x) && (v == other.v) && (f == other.f) &&
         (type == other.type) && (m == other.m) && (old_f == other.old_f);
}

/**
 * adds Particle to an given stream as string
 * @param stream stream
 * @param p particle
 * @return stream
 */
std::ostream &operator<<(std::ostream &stream, Particle &p) {
  stream << p.toString();
  return stream;
}

/**
 * sets position coordinates of Particle
 * @param x_arg new position coordinates
 */
void Particle::setX(std::array<double, 3> x_arg) {
   x = x_arg;
 }

/**
* sets previous position coordinates of Particle
* @param x_arg old position coordinates
*/
void Particle::setOldX(std::array<double, 3> newOldX) {
    oldX = newOldX;
}

 /**
  * sets velocity of Particle
  * @param v_arg new velocity
  */
void Particle::setV(std::array<double, 3> v_arg) {
  v = v_arg; 
}

/**
 * sets force of Particle
 * @param f_arg new force
 */
void Particle::setF(std::array<double, 3> f_arg){
  f = f_arg;
}

/**
 * sets old force of Particle
 * @param old_f_arg old force
 */
void Particle::setOldF(std::array<double, 3> old_f_arg) {
  old_f = old_f_arg;
}

