//
// Created by maraconda on 02.11.23.
//

#include <iostream>
#include "ParticleContainer.h"

ParticleContainer::ParticleContainer() {
    std::cout << "Empty Particle Container generated!" << std::endl;
}

ParticleContainer::ParticleContainer(const ParticleContainer &other) {
    containedParticles = other.containedParticles;
    numberOfParticles = other.numberOfParticles;
    std::cout << "Particle Container generated by copy!" << std::endl;
}

ParticleContainer::~ParticleContainer() = default;

void ParticleContainer::addParticle(const Particle &particle) {
    containedParticles.push_front(particle);
    numberOfParticles++;
}
