name: github-actions
run-name: Hi, my name is ${{ github.actor }}. You're probably wondering how I got here.
on:
  push:
    branches: main
  pull_request:
    branches: main

env :
  BUILD_TYPE : RELEASE


jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - name: Check out code
        uses: actions/checkout@main
      - name : you need a cache
        run : make ${{ github.workspace }}/cmake
      - name : build cmake now at least
        run : cmake --build . --config ${{env.BUILD_TYPE}}
      - name : compile gtest and they youre doneee
        run : g++ -out -I . -I ./tests *.cpp -lgtest -lpthread -fsanitize=address





