name: github-actions
run-name: Hi, my name is ${{ github.actor }}. You're probably wondering how I got here.
on:
  push:
    branches: main
  pull_request:
    branches: main

env :
  BUILD_TYPE : RELEASE


jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - name: Check out code
        uses: actions/checkout@main
      - name : go into cmake folder
        run : cmake --build tests
      - name : compile gtest and then youre done
        run : g++ -out -I . -I ./tests *.cpp -lgtest -lpthread -fsanitize=address






